export const RECEIVE_LOCATION_SUCCESS = 'RECEIVE_LOCATION_SUCCESS';
export const RECEIVE_LOCATION_FAIL = 'RECEIVE_LOCATION_FAIL';

export const RECEIVE_WEATHER_SUCCESS = 'RECEIVE_WEATHER_SUCCESS';
export const RECEIVE_WEATHER_FAIL = 'RECEIVE_WEATHER_FAIL';
